"""
This code was mainly generated by AI
and then manually edited to fit assignment specifications.
"""

import json
import os
from pathlib import Path

from config import (
    INDEX_ROOT,
    LEXICON_PATH,
    DOC_META_PATH,
)

from analytics_store import (
    ANALYTICS_PATH,
    DEFAULT_ANALYTICS
)

def load_json(path):
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)

def compute_index_size_kb():
    total = 0
    for root, _, files in os.walk(INDEX_ROOT):
        for f in files:
            total += os.path.getsize(os.path.join(root, f))
    return round(total / 1024, 2)

def compute_analytics():
    # Load index metadata
    lexicon = load_json(LEXICON_PATH)
    doc_meta = load_json(DOC_META_PATH)

    # Load existing analytics if present (to preserve search stats)
    if ANALYTICS_PATH.exists():
        analytics = load_json(ANALYTICS_PATH)
    else:
        analytics = DEFAULT_ANALYTICS.copy()

    # Compute indexing analytics
    num_docs = len(doc_meta)
    num_unique_tokens = len(lexicon)
    index_size_kb = compute_index_size_kb()

    # Count duplicates and near-duplicates separately
    num_duplicates = 0
    num_near_duplicates = 0

    for meta in doc_meta.values():
        dup = meta.get("duplicate_of")
        if dup is not None:
            num_duplicates += 1
            # If you want to distinguish exact vs near-duplicate:
            # exact duplicates have duplicate_of >= 0 AND same content hash
            # but since your indexer does not store exact-vs-near separately,
            # treat all as near-duplicates for now.
            num_near_duplicates += 1

    analytics["indexing"] = {
        "num_documents": num_docs,
        "num_unique_tokens": num_unique_tokens,
        "index_size_kb": index_size_kb,
        "num_duplicates": num_duplicates,
        "num_near_duplicates": num_near_duplicates,
    }

    # Save updated analytics
    with ANALYTICS_PATH.open("w", encoding="utf-8") as f:
        json.dump(analytics, f, indent=2)

    print("Analytics written to analytics.json")

if __name__ == "__main__":
    compute_analytics()
