"""
This code was mainly generated by AI
and then manually edited to fit assignment specifications.
"""

import analytic_io  # module for loading/saving analytics.json

def record_query_time(elapsed_ms):
    data = analytic_io.load_analytic()         # load analytics (preserves indexing stats)
    s = data["search"]                         # reference search analytics section

    s["total_queries"] += 1                    # increment query count

    n = s["total_queries"]                     # number of queries so far
    old_avg = s["avg_query_time_ms"]           # previous running average
    s["avg_query_time_ms"] = ((old_avg * (n - 1)) + elapsed_ms) / n  # online mean update

    if s["min_query_time_ms"] is None or elapsed_ms < s["min_query_time_ms"]:
        s["min_query_time_ms"] = elapsed_ms    # update fastest query

    if elapsed_ms > s["max_query_time_ms"]:
        s["max_query_time_ms"] = elapsed_ms    # update slowest query

    analytic_io.save_analytic(data)            # write updated analytics back to disk
